disabled_rules: # rule identifiers to exclude from running
  - trailing_whitespace
  - colon
  - variable_name
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
line_length: 250
variable_name:
  min_length: # only min_length
    error: 4 # only error
  excluded: # excluded via string array
    - id
    - db
    - map