language: swift
osx_image: xcode6.4
env:
         - LC_CTYPE=en_US.UTF-8 LANG=en_US.UTF-8
before_install:
         - gem install xcpretty -N
script:
         - xcodebuild -workspace Spots.xcworkspace -scheme "Spots" -destination "platform=iOS Simulator,name=iPhone 6,OS=lastest" test | xcpretty -c

